---
title: "TBSS FIgures"
author: "Daniela Cossio"
date: "09/14/2023"
mainfont: Times
output:
   html_document:
    toc: true
    toc_float: true
    toc_depth: 6
    theme: flatly
---

``` {r, libraries, echo=FALSE, results='hide',message=FALSE}
library(ggplot2)
#(plyr)
library(tidyverse)
# library(dplyr)
# library(tidyr)
library(stringr)
library(kableExtra)
# library(data.table)
# library(network)
# library(tidygraph)
# library(ggraph)
# library(igraph)
# library(networkD3)
# library(CINNA)
# library(umap)
# library(plotly)
#library(factoextra)
#library(lsr)
# library(car)
library(ggpubr)
#library(entropy)
#library(ds4psy)
# library(pROC)
#library(devtools)
#library(BRRR)
#library(stats)
#library(afex)
library(knitr)
library(janitor)
library(car)
library(ggiraph)
library(ggiraphExtra)
library(moonBook)
library(nationalparkcolors)
library(gridExtra)
library(markdown)
library(ppcor)
library(mediation)
library(paletteer)

```

```{r REad in our CSVS, echo=FALSE, results='hide',message=FALSE}

# Lets read in our subject information
top_workdir <-"/Users/danielacossio/Documents/Chrastil_Lab/Projects/SNAG/MIDLIFE_TBSS/"
  # laptop path "/Users/danielacossio/Library/CloudStorage/GoogleDrive-dcossio1@uci.edu/Other computers/My iMac/Chrastil_Lab/Projects/SNAG/MIDLIFE_TBSS/"

ROIs <- read.table(paste0(top_workdir,"JHU-WhiteMatter-labels-1mm.txt")) %>% dplyr::select(V2)

sub_info_master <- read.csv(paste0(top_workdir,"subject_info.csv"))

raw_FA <- read.csv(paste0(top_workdir,"JHU-skeletonized-FA.csv"), header=FALSE) %>% remove_empty(. ,which = "cols") %>% `colnames<-`(c(ROIs$V2)) 

raw_MD <- read.csv(paste0(top_workdir,"JHU-skeletonized-MD.csv"))  %>% remove_empty(. ,which = "cols") %>% `colnames<-`(c(ROIs$V2))

raw_AD <- read.csv(paste0(top_workdir,"JHU-skeletonized-AD.csv")) %>% remove_empty(. ,which = "cols") %>% `colnames<-`(c(ROIs$V2))

raw_RD <- read.csv(paste0(top_workdir,"JHU-skeletonized-RD.csv")) %>% remove_empty(. ,which = "cols") %>% `colnames<-`(c(ROIs$V2))

FA <- cbind(sub_info_master,raw_FA)

```


```{r, Loop DEgrees TRaveled fornix}

FA_temp <- FA %>% filter(!is.na(FA[["loop_de_rad3_degree"]]))
fem_FA_temp <- FA %>% filter(!is.na(FA[["loop_de_rad3_degree"]])) %>% filter(sex == "Female")
resid1 <- lm(loop_de_rad3_degree ~`Cingulum_(cingulate_gyrus)_L`+ age_scan_years, data = fem_FA_temp)

model1 <- lm(loop_de_rad3_degree ~`Fornix_(column_and_body_of_fornix)`+ sex.1 +age_scan_years, data = FA_temp)
ggplot(FA_temp, 
             aes(x = `Fornix_(column_and_body_of_fornix)`,
                 y = loop_de_rad3_degree)) +
  geom_point() +
  geom_smooth(method = "lm",
              mapping = aes(y = predict(model1, FA_temp))) 

 

plot(fem_FA_temp$loop_de_rad3_degree, resid1)

resid2 <- resid(lm(loop_de_rad3_degree ~ `Fornix_(column_and_body_of_fornix)`+ sex.1 +age_scan_years, data = FA_temp))

plot(FA_temp$loop_de_rad3_degree, resid2)


plot(lm(loop_de_rad3_degree ~   `Cingulum_(cingulate_gyrus)_L` + age_scan_years, data = fem_FA_temp))

ggplot(FA_temp,aes(y=loop_de_rad3_degree,x=`Cingulum_(cingulate_gyrus)_R`,color=sex,1))+geom_point()+
   geom_smooth(formula = y ~ x, method = "lm")+
   labs(x= "Quantitative Anisotropy", y= "Proportion of correct trials" ) +
   theme(legend.position = "none") +
    stat_cor(method = "spearman", label.x.npc = 0.70, label.y.npc = 1) +
    stat_regline_equation( aes(label = ..rr.label..)) +
    font("xlab", size=30)+
    font("ylab", size=30)
```

