---
title: "ShapeAnalysis_summer2023"
author: "Daniela Cossio"
date: "7/25/2023"
output: html_document
---

```{r setup, echo=FALSE, results='hide',message=FALSE}
library(ggplot2)
#(plyr)
library(tidyverse)
# library(dplyr)
# library(tidyr)
library(stringr)
# library(data.table)
# library(network)
# library(tidygraph)
# library(ggraph)
# library(igraph)
# library(networkD3)
# library(CINNA)
# library(umap)
# library(plotly)
library(factoextra)
library(lsr)
# library(car)
library(ggpubr)
library(entropy)
#library(ds4psy)
# library(pROC)
library(devtools)
library(BRRR)
library(stats)
library(afex)
library(nationalparkcolors) # for palettes
library(wesanderson)



knitr::opts_chunk$set(warning=FALSE, message=FALSE, echo = FALSE)

```

```{r paths and lists, echo=FALSE, results='hide',message=FALSE }

work_dir <- "/Users/danielacossio/Desktop/Shape_analysis/"

data_dir<- "/Users/danielacossio/Desktop/Shape_analysis/output/"

#ROIS <- read.table(paste0(work_dir,"HCp842ROIS.txt"))

rows2grab <- c("number of tracts","mean length(mm)","diameter(mm)", "volume(mm^3)")

subfiles <- list.dirs(path = data_dir, full.names = FALSE,recursive = FALSE)

roi_cols <- list.dirs(path = "/Users/danielacossio/Desktop/Shape_analysis/output/sub-301", full.names = FALSE,recursive = FALSE)


SubInfo <- read.csv(paste0(work_dir,"/maze_subinfo.csv"), header=TRUE) %>% rename("subjects" ="subject_id")


HormonesSubInfo <- read.csv(paste0(work_dir,"/hormone_subs.csv"), header=TRUE) %>% filter(sex =="Female") 
```

```{r functions}
ChangeSubIDFormat<- function(df){
  for (sub in 1:nrow((df))) { 
    clean_subnum <- str_split(df$subjects[sub], "_")[[1]][1]  %>% str_split("-") %>% as.data.frame() %>% `[`(2,) 
  df$subjects[sub] <-  sub("^0+", "", clean_subnum) 
 
  }
  return(df)
}



```


```{r Preprocesssing}
# this will create one CSV for each VAriable only need to do once.
# 
#  #KEEP but CHANGE
# 
# for(Shape_Var in 1:length(rows2grab)){
# 
#   print (rows2grab[Shape_Var]) # grab variable
#   master_DF <- as.data.frame(matrix(ncol = length(roi_cols)+1, nrow = length(subfiles))) # create master DF for Variable
#     
#   for(sub in 1:length(subfiles)){
# 
#     print(paste("running subject",subfiles[sub]))
# 
#     subject_df <- as.data.frame(matrix(ncol = length(roi_cols)+1, nrow = 1))
#     subject_df[,1] <- subfiles[sub] #KEEP but CHANGE
#     
#     ROIS <- list.dirs(path = paste0(data_dir,subfiles[sub]), full.names = FALSE,recursive = FALSE)
#     
#     for( roi in 1:length(ROIS)){
#       print(paste("running ",ROIS[roi]))
#       
#       ROI_path <- paste0(data_dir,subfiles[sub],"/",ROIS[roi])
#       
#       #Check if folder is empty 
#       if (length(list.files(path = ROI_path, pattern = "*.txt")) == 0){
#         print("no ouput. skipping ROI")
#         subject_df[,roi+1] <- NA
#         next
#       }
#       
#       # Checking that the text file is not empty.
#       Text_path <- list.files(path = ROI_path, pattern = "*.txt")
#       
#       if (file.size(paste0(ROI_path,"/",Text_path)) > 0 ){
#         print("File Exists lets read it in")
#         ROI_txt <- read.delim(paste0(ROI_path,"/",Text_path), header=FALSE) 
#         subject_df[,roi+1] <- ROI_txt %>% filter(V1 ==rows2grab[Shape_Var]) %>% pull(V2)
#         }
#       else{
#         print("File does not exist. Add NA instead")
#         subject_df[,roi+1] <- NA #KEEP but CHANGE
#         }
#     }
#     
#     master_DF[sub,] <- subject_df[1,]
#   }
#   colnames(master_DF) <- c("subjects",ROIS) 
#   txt_name <- paste0(gsub(" ", "_",rows2grab[Shape_Var]),"_cleaned.csv")
#   write.csv(master_DF, paste0(work_dir,txt_name), row.names=FALSE)
# }



```


```{r Reading in CSVs}
MeanLength <- read.csv(paste0(work_dir,"/mean_length(mm)_cleaned.csv")) %>% ChangeSubIDFormat() 
NumTracts <- read.csv(paste0(work_dir,"/number_of_tracts_cleaned.csv"))%>% ChangeSubIDFormat()
diameter <- read.csv(paste0(work_dir,"/diameter(mm)_cleaned.csv"))%>% ChangeSubIDFormat()
Volume <-  read.csv(paste0(work_dir,"/volume(mm^3)_cleaned.csv")) %>% ChangeSubIDFormat()                    

Volume$subjects <- as.integer(Volume$subjects)
MeanLength$subjects <- as.integer(MeanLength$subjects)
NumTracts$subjects <- as.integer(NumTracts$subjects)
diameter$subjects <- as.integer(diameter$subjects)
```

```{r Do aspects of White matter shape corrlate to hormones? }

#Let's grab  grab the correct subjects for volume
HormonesSubInfo <- HormonesSubInfo %>% rename("subjects" ="subject_id")
#Estrogen
Est_DF <- inner_join(HormonesSubInfo,Volume)
  
#Lets check normality 
forn_normal <- shapiro.test(Est_DF$Fornix_L) #Normal 
fornR_normal <- shapiro.test(Est_DF$Fornix_R) #Not Normal


FornixVol.Est.lm <- lm(Est_DF$Fornix_L ~ Est_DF$estradiol_scan_pg_ml)
summary(FornixVol.Est.lm)
```

```{r Analyze sex differences between groups}


male_DF <- inner_join(MeanLength, SubInfo) %>% filter(sex ==1) 
femaleDF <- inner_join(MeanLength, SubInfo) %>% filter(sex ==0) # create master DF for Variable

Masternorm <- as.data.frame(matrix(ncol = 3, nrow = length(roi_cols)+1)) %>% `colnames<-`(c("ROI","male", "female"))
MasterTtest <- as.data.frame(matrix(ncol = 2, nrow = length(roi_cols)+1))

for (sex in c("male", "female")){
  print(sex)
  
   temp_df <- as.data.frame(matrix(ncol = 1, nrow = length(roi_cols)+1))
  
  for (roi in 1:length(roi_cols)){
    Masternorm[roi,1] <- roi_cols[roi]
    #run normality
    if (sex =="male"){
      norm <- shapiro.test(male_DF[,roi])
    }
    if (sex =="female"){
    norm <- shapiro.test(femaleDF[,roi])
    }

    temp_df[roi,1] <- norm$p.value
  }
  
   Masternorm[sex] <- temp_df$V1
  }
 




```







```{r MAze Male and female}

SubInfo <- SubInfo %>% rename("subjects" ="subject_id")
Maze_vol <- inner_join(SubInfo,Volume)
Maze_len <- inner_join(SubInfo,MeanLength)
Maze_numtracts <- inner_join(SubInfo,NumTracts)
Maze_diameter <- inner_join(SubInfo,diameter)

# Let's just see if there are any sex differences 



lm <- lm(Maze_len$Corpus_Callosum_Body ~ Maze_len$maze_accuracy_pct + Maze_len$sex * Maze_len$age_scan_years)
summary(lm)


# Create a Loop for all this

# Let's choose our ROIs

ROIs <- c("Cingulum_Frontal_Parahippocampal_L","Cingulum_Frontal_Parahippocampal_R",     "Cingulum_Frontal_Parietal_L","Cingulum_Frontal_Parietal_R","Cingulum_Parahippocampal_L",            
"Cingulum_Parahippocampal_Parietal_L","Cingulum_Parahippocampal_Parietal_R", 
"Cingulum_Parahippocampal_R" ,"Cingulum_Parolfactory_L",           
"Cingulum_Parolfactory_R","Fornix_L", "Fornix_R")



# Fornix L
AnalyzeROI("Fornix_L",Maze_len)

ggplot(data = Maze_len, aes(x = Fornix_L, y = log(maze_accuracy_pct))) +
  geom_point(aes(shape = factor(sex))) +
  geom_point(aes(color = factor(sex)))

#not sig
Fornix_len.lm <- lm(Maze_len$Fornix_L ~ Maze_len$maze_accuracy_pct + Maze_len$sex)
summary(Fornix_len.lm)

#do men and women have diff tract lengths?
maleMazeVars <- Maze_len %>% filter(sex==1) 
femaleMazeVars <- Maze_len %>% filter(sex==0) 
mazesexdif <- cbind(maleMazeVars,femaleMazeVars)

ggplot(Maze_len)+
  aes(x = sex, y = Fornix_R, group=sex) +
  geom_boxplot(fill = "#0c4c8a") +
  theme_minimal()

shapiro.test(maleMazeVars$Fornix_R)

t.test(maleMazeVars$Fornix_R,femaleMazeVars$Fornix_R)



# cing
ggplot(data = Maze_vol, aes(x = Cingulum_Frontal_Parietal_L, y = log(maze_accuracy_pct))) +
  geom_point(aes(shape = factor(sex))) +
  geom_point(aes(color = factor(sex)))

ggplot(data = Maze_len, aes(x = Cingulum_Frontal_Parietal_L, y = log(maze_accuracy_pct))) +
  geom_point(aes(shape = factor(sex))) +
  geom_point(aes(color = factor(sex)))




```


