---
title: "LOOP Notes and Analyses"
author: "Daniela Cossio"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
    html_document:
    toc: true
    toc_float: true
    toc_depth: 2
    classoption:
    - twocolumn
---

```{r adding libraries,echo=FALSE, results='hide',message=FALSE}
library(ggplot2)
#(plyr)
library(tidyverse)
# library(dplyr)
# library(tidyr)
library(stringr)
library(kableExtra)
# library(data.table)
# library(network)
# library(tidygraph)
# library(ggraph)
# library(igraph)
# library(networkD3)
# library(CINNA)
# library(umap)
# library(plotly)
#library(factoextra)
#library(lsr)
# library(car)
library(ggpubr)
#library(entropy)
#library(ds4psy)
# library(pROC)
#library(devtools)
#library(BRRR)
#library(stats)
#library(afex)
library(knitr)
library(janitor)
library(car)
library(ggiraph)
library(ggiraphExtra)
library(moonBook)
library(nationalparkcolors)
library(gridExtra)
library(markdown)
```



```{css, echo=FALSE}
TOC {
  color: #F6B2DB;
  font-family: Arial;
  font-size: "16px"; 
  border-color: #F6B2DB;
}

h1.title {
  color: black ;
  font-family: Arial;
  font-size: "72px";
  padding: "10px 0";
  background-color: #F6B2DB ;
  text-align: center;
}

h4.date {
  color: black ;
  font-family: Arial;
  font-size: "34px";
  text-align: center;
}

h4.author {
  color: black;
  font-size: "34px";
  font-family: Arial;
  text-align: center;
}


h1,h2, h3, h4, h5 ,h6 {
  text-align: center;
  font-family: Arial;
  
}

body, p, h2{
  color: black; 
  font-family: Arial;
}

hr {
  height:5px;
  border-width:0;
  background-color: black ;
}



```



# Reading in and prepping our data 

```{r reading in our CSVs, echo=FALSE, results='hide',message=FALSE}
working_dir <- "/Users/danielacossio/Documents/Chrastil_Lab/Projects/SNAG/DSI_rerun_data/DSP/"

rows2grab <- c("Tract Name", "number of tracts","mean length(mm)","diameter(mm)", "volume(mm^3)")

sub_info <- read.csv("/Users/danielacossio/Documents/Chrastil_Lab/Projects/SNAG/DSI_rerun_data/subject_info.csv")
```
