---
title: "Creating Figures for VR output BY Daniela Cossio"
output: html_notebook
---

```{r}
########################################################################
##       Figure: For creating figures for midlife VR output           ##  
##       data input :                                                 ##
##                                                                    ##
##                                                                    ##
########################################################################

#Load libraries
library(ggplot2)

```

```{r setup, include=FALSE}

# setting our workdir

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir="/Volumes/GoogleDrive/My Drive/Midlife_walkingVR_Pilot/midlifeVRpilot_2022/behavior_data/Preprocessed")
```

```{r}

# uploading your data that you want to visualize 

df <- read.csv("/Volumes/GoogleDrive/My Drive/Midlife_walkingVR_Pilot/midlifeVRpilot_2022/behavior_data/Preprocessed/MazeGraph/GRAPHParticipant.csv")

```


```{r}

# Stats




```
 
 
 
 
```{r}
# plotting frequency 
# change bin width for data 

jpeg("Graph Acc.jpg")

ggplot(df,aes(x=accuracy)) + 
         geom_histogram(binwidth = 0.2, color="black", fill="pink")+
         geom_vline(aes(xintercept=mean(accuracy)), color="black", linetype="dashed", size=1)+
         labs(x="accuracy", y="number of participants")+ 
         ggtitle(" graph accuracy")
dev.off
      

```

